USE [PlaceHolder]
GO
DELETE FROM BANGDIEM
DELETE FROM DIEM
DELETE FROM CHITIETBAOCAOMON
DELETE FROM BAOCAOMONHOC
DELETE FROM XEPLOP
DELETE FROM HOSOHOCSINH
DELETE FROM CHITIETBAOCAOHOCKY
DELETE FROM BAOCAOHOCKY
DELETE FROM LOP
DELETE FROM NAMHOC