//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frMain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("frMain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///DELETE FROM BANGDIEM
        ///DELETE FROM DIEM
        ///DELETE FROM LOAIDIEM
        ///DELETE FROM CHITIETBAOCAOMON
        ///DELETE FROM BAOCAOMONHOC
        ///DELETE FROM MONHOC
        ///DELETE FROM XEPLOP
        ///DELETE FROM HOSOHOCSINH
        ///DELETE FROM CHITIETBAOCAOHOCKY
        ///DELETE FROM BAOCAOHOCKY
        ///DELETE FROM GIANGDAY
        ///DELETE FROM THOIKHOABIEU
        ///DELETE FROM GIAOVIEN
        ///DELETE FROM LOP
        ///DELETE FROM KHOI
        ///DELETE FROM NAMHOC
        ///DELETE FROM THAMSO
        ///DELETE FROM HOCKY.
        /// </summary>
        internal static string DeleteDataAllTables {
            get {
                return ResourceManager.GetString("DeleteDataAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HuongDanSuDungPhanMem {
            get {
                object obj = ResourceManager.GetObject("HuongDanSuDungPhanMem", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
