//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectToDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectToDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from sys.tables where        ///exists (select * from sys.tables where name = &apos;NAMHOC&apos;)         ///and exists (select * from sys.tables where name = &apos;HOCKY&apos;)         ///and exists (select * from sys.tables where name = &apos;KHOI&apos;)         ///and exists (select * from sys.tables where name = &apos;LOP&apos;)         ///and exists (select * from sys.tables where name = &apos;HOSOHOCSINH&apos;)         ///and exists (select * from sys.tables where name = &apos;XEPLOP&apos;)         ///and exists (select * from sys.tables where name = &apos;MONHOC&apos;)         ///and exists (select * from sys.tables where name = &apos;LOAIDIEM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckTable {
            get {
                return ResourceManager.GetString("CheckTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///
        ///CREATE TABLE NAMHOC
        ///(
        ///	NAMHOC VARCHAR(10) PRIMARY KEY,
        ///)
        ///
        ///CREATE TABLE HOCKY
        ///(
        ///	MAHOCKY int primary key,
        ///	TENHOCKY nvarchar(30) not null,
        ///)
        ///CREATE TABLE KHOI
        ///(	
        ///	MAKHOI varchar(3) primary key,
        ///	KHOI nvarchar(10) not null,
        ///)
        ///CREATE TABLE LOP
        ///(
        ///	MALOP int primary key,
        ///	MAKHOI varchar(3) FOREIGN KEY REFERENCES KHOI(MaKhoi) ON DELETE CASCADE,
        ///	TENLOP nvarchar(50)not null,
        ///	NAMHOC VARCHAR(10) FOREIGN KEY REFERENCES NAMHOC(NAMHOC) ON DELETE CASCADE,
        ///	SISO int not null [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///DELETE FROM BANGDIEM
        ///DELETE FROM DIEM
        ///DELETE FROM LOAIDIEM
        ///DELETE FROM CHITIETBAOCAOMON
        ///DELETE FROM BAOCAOMONHOC
        ///DELETE FROM MONHOC
        ///DELETE FROM XEPLOP
        ///DELETE FROM HOSOHOCSINH
        ///DELETE FROM CHITIETBAOCAOHOCKY
        ///DELETE FROM BAOCAOHOCKY
        ///DELETE FROM GIANGDAY
        ///DELETE FROM THOIKHOABIEU
        ///DELETE FROM GIAOVIEN
        ///DELETE FROM LOP
        ///DELETE FROM KHOI
        ///DELETE FROM NAMHOC
        ///DELETE FROM THAMSO
        ///DELETE FROM HOCKY.
        /// </summary>
        internal static string DeleteDataAllTables {
            get {
                return ResourceManager.GetString("DeleteDataAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///DELETE FROM BANGDIEM
        ///DELETE FROM DIEM
        ///DELETE FROM CHITIETBAOCAOMON
        ///DELETE FROM BAOCAOMONHOC
        ///DELETE FROM XEPLOP
        ///DELETE FROM HOSOHOCSINH
        ///DELETE FROM CHITIETBAOCAOHOCKY
        ///DELETE FROM BAOCAOHOCKY
        ///DELETE FROM GIANGDAY
        ///DELETE FROM THOIKHOABIEU
        ///DELETE FROM GIAOVIEN
        ///DELETE FROM LOP
        ///DELETE FROM NAMHOC.
        /// </summary>
        internal static string DeleteDataTables {
            get {
                return ResourceManager.GetString("DeleteDataTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///
        ///SET DATEFORMAT DMY
        ///
        ///INSERT INTO NAMHOC VALUES (&apos;2010-2011&apos;)
        ///INSERT INTO LOP VALUES (0,&apos;K10&apos;,&apos;10A1&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (1,&apos;K10&apos;,&apos;10A2&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (2,&apos;K10&apos;,&apos;10A3&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (3,&apos;K10&apos;,&apos;10A4&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (4,&apos;K11&apos;,&apos;11A1&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (5,&apos;K11&apos;,&apos;11A2&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (6,&apos;K11&apos;,&apos;11A3&apos;,&apos;2010-2011&apos;,0)
        ///INSERT INTO LOP VALUES (7,&apos;K12&apos;,&apos;12A1&apos;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitData {
            get {
                return ResourceManager.GetString("InitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [PlaceHolder]
        ///GO
        ///
        ///IF OBJECT_ID(N&apos;[dbo].[usp_InsertBangdiem]&apos;) IS NOT NULL
        ///	DROP PROCEDURE [dbo].[usp_InsertBangdiem]
        ///
        ///IF OBJECT_ID(N&apos;[dbo].[usp_InsertBangdiemNull]&apos;) IS NOT NULL
        ///	DROP PROCEDURE [dbo].[usp_InsertBangdiemNull]
        ///
        ///IF OBJECT_ID(N&apos;[dbo].[usp_UpdateBangdiem]&apos;) IS NOT NULL
        ///	DROP PROCEDURE [dbo].[usp_UpdateBangdiem]
        ///
        ///IF OBJECT_ID(N&apos;[dbo].[usp_DeleteBangdiem]&apos;) IS NOT NULL
        ///	DROP PROCEDURE [dbo].[usp_DeleteBangdiem]
        ///
        ///IF OBJECT_ID(N&apos;[dbo].[usp_SelectBangdiem]&apos;) IS NOT NULL
        ///	DROP PROC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StroredProcedures {
            get {
                return ResourceManager.GetString("StroredProcedures", resourceCulture);
            }
        }
    }
}
