USE [PlaceHolder]
GO
DELETE FROM BANGDIEM
DELETE FROM DIEM
DELETE FROM LOAIDIEM
DELETE FROM CHITIETBAOCAOMON
DELETE FROM BAOCAOMONHOC
DELETE FROM MONHOC
DELETE FROM XEPLOP
DELETE FROM HOSOHOCSINH
DELETE FROM CHITIETBAOCAOHOCKY
DELETE FROM BAOCAOHOCKY
DELETE FROM GIANGDAY
DELETE FROM THOIKHOABIEU
DELETE FROM GIAOVIEN
DELETE FROM LOP
DELETE FROM KHOI
DELETE FROM NAMHOC
DELETE FROM THAMSO
DELETE FROM HOCKY