<?xml version="1.0" encoding="utf-8"?><Database Name="APPDATA" Class="AppDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\APPDATA.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="DataAccessObject.Properties.Settings" SettingsPropertyName="APPDATAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MATK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTK" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="LOAITK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.usp_DeleteTaiKhoan" Method="usp_DeleteTaiKhoan">
    <Parameter Name="MATK" Parameter="mATK" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_UpdateTaiKhoan" Method="usp_UpdateTaiKhoan">
    <Parameter Name="MATK" Parameter="mATK" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENTK" Parameter="tENTK" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="MATKHAU" Parameter="mATKHAU" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="LOAITK" Parameter="lOAITK" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_InsertTaiKhoan" Method="usp_InsertTaiKhoan">
    <Parameter Name="MATK" Parameter="mATK" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENTK" Parameter="tENTK" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="MATKHAU" Parameter="mATKHAU" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="LOAITK" Parameter="lOAITK" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_SelectLastMaTK" Method="usp_SelectLastMaTK">
    <ElementType Name="usp_SelectLastMaTKResult">
      <Column Name="MATK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_SelectTaikhoan" Method="usp_SelectTaikhoan">
    <Parameter Name="MATK" Parameter="mATK" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_SelectTaikhoanResult">
      <Column Name="MATK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENTK" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="LOAITK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>